name: Setup GitHub Runner on Server

on:
  workflow_dispatch:
    inputs:
      host:
        type: string
        description: 'Server host'
        required: true
      port:
        type: string
        description: 'SSH port'
        required: true
        default: '22'
      password:
        type: string
        description: 'SSH root password'
        required: true
      runner_token
        type: string
        description: 'GitHub Runner Token'
        required: true
      runner_version:
        type: string
        description: 'GitHub Runner version'
        required: false
        default: 'latest'
      runner_workdir:
        type: string
        description: 'GitHub Runner work directory'
        required: true
        default: '/aosp_build'
      runner_user:
        type: string
        description: 'GitHub Runner user'
        required: true
        default: 'neokoni'
      mount_disk:
        type: string
        description: 'Should mount additional disk, fill disk path if true'
        required: false

jobs:
  setup_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Runner Version
        run: |
          if [[ ${{ github.event.inputs.runner_version }} == 'latest' ]];
          then
            echo "Using latest GitHub Runner version"
            RUNNER_VERSION=$(curl -s https://api.github.com/repos/actions/runner/releases/latest | grep 'tag_name' | cut -d\" -f4 | sed 's/v//')
          else
            echo "Using specified GitHub Runner version: ${{ github.event.inputs.runner_version }}"
            RUNNER_VERSION=${{ github.event.inputs.runner_version }}
          fi
          echo "RUNNER_VERSION=$RUNNER_VERSION" >> $GITHUB_ENV

      - name: Setup User and Workdir
        run: |
          echo "RUNNER_USER=${{ github.event.inputs.runner_user }}" >> $GITHUB_ENV
          echo "RUNNER_WORKDIR=${{ github.event.inputs.runner_workdir }}" >> $GITHUB_ENV

      - name: Install GitHub Runner
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ github.event.inputs.host }}
          username: root
          password: ${{ github.event.inputs.password }}
          port: ${{ github.event.inputs.port }}
          script: |
            #!/bin/bash

            cd /opt || exit

            # Setup User and Workdir
            useradd -m -s /bin/bash ${{ github.event.inputs.runner_user }} || true
            mkdir -p ${{ github.event.inputs.runner_workdir }} || true

            if [ -z ${{ github.event.inputs.mount_disk }} ]; then
              echo "No additional disk to mount"
            else
              echo "Mounting additional disk at ${{ github.event.inputs.mount_disk }}"
              mkfs.btrfs -f /dev/${{ github.event.inputs.mount_disk }}
              mount /dev/${{ github.event.inputs.mount_disk }} ${{ github.event.inputs.runner_workdir }} -o noatime,compress=zstd
            fi

            chown -R ${{ github.event.inputs.runner_user }}:${{ github.event.inputs.runner_user }} ${{ github.event.inputs.runner_workdir }}
          
            # Get GitHub Runner
            echo "Installing GitHub Runner version ${{ env.RUNNER_VERSION }}"
            mkdir -p actions-runner && cd actions-runner
            curl -O -L https://github.com/actions/runner/releases/download/v${{ env.RUNNER_VERSION }}/actions-runner-linux-x64-${{ env.RUNNER_VERSION }}.tar.gz
            tar xzf ./actions-runner-linux-x64-${{ env.RUNNER_VERSION }}.tar.gz
            chown -R ${{ github.event.inputs.runner_user }}:${{ github.event.inputs.runner_user }} .

            # Configure the runner
            su ${{ github.event.inputs.runner_user }} -c "bash config.sh --url https://github.com/neokoni/ota --token ${{ github.event.inputs.runner_token }} --name neobuild --work ${{ env.RUNNER_WORKDIR }} --replace --unattended"
            bash svc.sh install
            bash svc.sh start

  